In [7]:
import numpy as np


checkerboard = np.array([
    [[1, 1, 0, 0],
     [1, 1, 0, 0],
     [1, 1, 0, 0]],
    [[1, 1, 0, 0],
     [1, 1, 0, 0],
     [1, 1, 0, 0]],
    [[0, 0, 1, 1],
     [0, 0, 1, 1],
     [0, 0, 1, 1]],
    [[0, 0, 1, 1],
     [0, 0, 1, 1],
     [0, 0, 1, 1]],
])
print(checkerboard.shape)

(4, 3, 4)


### Local averaging of the volume

In [16]:
filter3d = np.ones((2, 2, 2)) / 8

conv3d_height = checkerboard.shape[0] - filter3d.shape[0] + 1
conv3d_width = checkerboard.shape[1] - filter3d.shape[1] + 1
conv3d_depth = checkerboard.shape[2] - filter3d.shape[2] + 1

conv3d = np.zeros((conv3d_height, conv3d_width, conv3d_depth))
for i in range(conv3d_height):
    for j in range(conv3d_width):
        for k in range(conv3d_depth):
            conv3d[i, j, k] = np.sum(
                checkerboard[i:i + filter3d.shape[0], j:j + filter3d.shape[1], k:k + filter3d.shape[2]] * filter3d
            )

print(conv3d)

[[[1.  0.5 0. ]
  [1.  0.5 0. ]]

 [[0.5 0.5 0.5]
  [0.5 0.5 0.5]]

 [[0.  0.5 1. ]
  [0.  0.5 1. ]]]


### Edge detection

In [31]:
filter3d = np.array([
    [[1, -1],
     [1,-1]],
    [[1, -1],
     [1,-1]],
])

conv3d_height = checkerboard.shape[0] - filter3d.shape[0] + 1
conv3d_width = checkerboard.shape[1] - filter3d.shape[1] + 1
conv3d_depth = checkerboard.shape[2] - filter3d.shape[2] + 1

conv3d = np.zeros((conv3d_height, conv3d_width, conv3d_depth))
for i in range(conv3d_height):
    for j in range(conv3d_width):
        for k in range(conv3d_depth):
            conv3d[i, j, k] = np.sum(
                checkerboard[i:i + filter3d.shape[0], j:j + filter3d.shape[1], k:k + filter3d.shape[2]] * filter3d
            )
print(conv3d)


[[[ 0.  4.  0.]
  [ 0.  4.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0. -4.  0.]
  [ 0. -4.  0.]]]


In [29]:
filter3d_x = np.array([
    [[ 1,  0, -1], 
     [ 2,  0, -2], 
     [ 1,  0, -1]],
    
    [[ 1,  0, -1], 
     [ 2,  0, -2], 
     [ 1,  0, -1]],
])  # 检测 X 方向边缘
# Y 方向边缘检测
filter3d_y = np.array([
    [[ 1,  2,  1], 
     [ 0,  0,  0], 
     [-1, -2, -1]],
    
    [[ 1,  2,  1], 
     [ 0,  0,  0], 
     [-1, -2, -1]],
])

# Z 方向边缘检测
filter3d_z = np.array([
    [[ 1,  1,  1], 
     [ 1,  1,  1], 
     [ 1,  1,  1]],
    
    [[-1, -1, -1], 
     [-1, -1, -1], 
     [-1, -1, -1]],
])

def conv3d(image, kernel):
    conv_height = image.shape[0] - kernel.shape[0] + 1
    conv_width = image.shape[1] - kernel.shape[1] + 1
    conv_depth = image.shape[2] - kernel.shape[2] + 1

    conv_result = np.zeros((conv_height, conv_width, conv_depth))
    for i in range(conv_height):
        for j in range(conv_width):
            for k in range(conv_depth):
                conv_result[i, j, k] = np.sum(
                    image[i:i + kernel.shape[0], j:j + kernel.shape[1], k:k + kernel.shape[2]] * kernel
                )
    return conv_result
edge_x = conv3d(checkerboard, filter3d_x)
edge_y = conv3d(checkerboard, filter3d_y)
edge_z = conv3d(checkerboard, filter3d_z)
total_edge = np.sqrt(edge_x ** 2 + edge_y ** 2 + edge_z ** 2)  # 计算总的梯度
#print(conv3d)
print(total_edge)

[[[8. 8.]]

 [[3. 3.]]

 [[8. 8.]]]


In [21]:
filter3d = np.array([
    [[1, -1],
     [1,-1]],
    [[1, -1],
     [1,-1]],
])
print(filter3d.shape)

(2, 2, 2)
